version: '2.1'

services:
  zookeeper-1:
    image: zookeeper
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_vol:/data
      - zookeeper_vol:/datalog
      - zookeeper_vol:/logs
  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "100.79.170.53"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_LOG_DIRS: "/kafka/logs"
    volumes:
      - kafka_vol:/kafka
    depends_on:
      - zookeeper-1

volumes:
  zookeeper_vol: { }
  kafka_vol: { }