server:
  port: 10000


spring:
  kafka:
    bootstrap-servers: 100.79.170.53:9092

    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
      bootstrap-servers: 100.79.170.53:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3

